### PR TITLE
Run analyze

### PR DESCRIPTION
**Pull request by shayonj**
Since its a new table, post rename, executing
an analyze

### CODE REVIEW

**Comment by jfrost** [comment]
Might be better to do before the swap, but 👍 .

**Comment by shayonj** [comment]
Yeah i was thinking about that. It could probably happen after replay and before swap. However, if the analyze takes a while, the process will need to continue to replay and then swap. pg_repack also does analyze in the end (no worries of cleanup either). Lets have this way for now, can be a feature req in future. I am also curious to do some stress testing (maybe pg_bench or similar). 

btw, really appreciate all the reviews, feel free to continue and I am more than happy to back-fill any feedback accordingly too 🙌🏾

**Comment by jfrost** [comment]
I suspect that when pg_repack does it at the end, it at least has the stats from the original table because of the way it does the swap by manipulating the catalog. In our case, because we're swapping via rename, I suspect we have no stats until after the ANALZYE, so the planner will assume 1 row in the table and then have poor plans.

**Comment by shayonj** [comment]
Thats true, pg_repack updates the ref file pointers which keeps other things a bit simple (relative) too. I was hoping to catch this on the stress test as well. 

I was thinking - we analyze once after the [copy](https://github.com/shayonj/pg-online-schema-change/blob/ea42007d578477f0db2ba2b73192ed28b7cc7502/lib/pg_online_schema_change/orchestrate.rb#L39) and once after the swap. This way, we won't have to do in between replay and swap and losing any time which may increase the delta (rows to be replayed) beyond 20 (ref). What do you think?

**Comment by jfrost** [comment]
Oh, I mentioned this in PR #8 but I think we can probably lean on autovacuum to do any analyzing that's required after the replay.

**Pull request merged**
